#!/usr/bin/env python3
"""Generate SQL migration for newsletter archive -> briefings table."""

import os
import re
from datetime import date

NEWSLETTER_ROOT = os.path.join(os.path.dirname(__file__), '..', 'newsletter')
OUTPUT_SQL = os.path.join(os.path.dirname(__file__), '..', 'api_layer', 'db', 'migrations', '002_briefings_newsletter_archive.sql')


def parse_og(html_path, tag):
    with open(html_path, encoding='utf-8') as f:
        content = f.read(8000)
    m = re.search(rf'property=["\']og:{tag}["\'][^>]*content=["\']([^"\']*)["\']', content)
    if not m:
        m = re.search(rf'content=["\']([^"\']*)["\'][^>]*property=["\']og:{tag}["\']', content)
    return m.group(1).strip() if m else None


def parse_file_date(filename):
    """Parse MMDDYYYY from filename, return date object."""
    base = os.path.basename(filename)
    m = re.match(r'^(\d{2})(\d{2})(\d{4})', base)
    if not m:
        return None
    mm, dd, yyyy = int(m.group(1)), int(m.group(2)), int(m.group(3))
    return date(yyyy, mm, dd)


def collect_editions():
    editions = []
    for root, dirs, files in os.walk(NEWSLETTER_ROOT):
        dirs.sort()
        for fname in sorted(files):
            if not fname.endswith('.html'):
                continue
            full = os.path.join(root, fname)
            d = parse_file_date(fname)
            if not d:
                print(f'  SKIP (no date): {fname}')
                continue
            # relative path from repo root
            rel = os.path.relpath(full, os.path.join(os.path.dirname(__file__), '..')).replace('\\', '/')
            editions.append((d, rel, full))

    editions.sort(key=lambda x: x[0])
    return editions


def escape_sql(s):
    if s is None:
        return 'NULL'
    return "'" + s.replace("'", "''") + "'"


def main():
    editions = collect_editions()
    print(f'Found {len(editions)} editions')

    lines = []
    lines.append("-- Migration 002 — Newsletter Archive into briefings table")
    lines.append("-- Generated by tools/generate_newsletter_migration.py")
    lines.append("-- Run: npm run db:migrate")
    lines.append("")
    lines.append("BEGIN;")
    lines.append("")
    lines.append("-- Add archive columns (idempotent)")
    lines.append("ALTER TABLE briefings ADD COLUMN IF NOT EXISTS edition_number INTEGER;")
    lines.append("ALTER TABLE briefings ADD COLUMN IF NOT EXISTS file_path TEXT;")
    lines.append("ALTER TABLE briefings ADD COLUMN IF NOT EXISTS description TEXT;")
    lines.append("CREATE UNIQUE INDEX IF NOT EXISTS idx_briefings_edition_number ON briefings (edition_number) WHERE edition_number IS NOT NULL;")
    lines.append("")
    lines.append("-- Insert archive records (upsert by edition_date)")
    lines.append("INSERT INTO briefings")
    lines.append("  (id, edition_date, edition_number, subject_line, description, body_md, file_path,")
    lines.append("   pipeline_status, published_at, threat_item_ids, innovation_item_ids, open_count, click_count)")
    lines.append("VALUES")

    rows = []
    for i, (d, rel_path, full_path) in enumerate(editions, start=1):
        subject = parse_og(full_path, 'title')
        desc = parse_og(full_path, 'description')

        # Strip date suffix from og:title for cleaner subject_line, e.g. "Title | Apr 22, 2026" -> "Title"
        if subject:
            subject = re.sub(r'\s*\|\s*\w+\.?\s+\d+,?\s+\d{4}$', '', subject).strip()
        if not subject:
            subject = f'CyberSense Daily Briefing — Edition {i}'

        body_md = desc if desc else subject
        pub_ts = f"{d.isoformat()} 12:00:00+00"

        row = (
            f"  (gen_random_uuid(), {escape_sql(d.isoformat())}, {i}, "
            f"{escape_sql(subject)}, {escape_sql(desc)}, {escape_sql(body_md)}, {escape_sql(rel_path)},\n"
            f"   'published', {escape_sql(pub_ts)}, '{{}}', '{{}}', 0, 0)"
        )
        rows.append(row)

    lines.append(',\n'.join(rows))
    lines.append("ON CONFLICT (edition_date) DO UPDATE SET")
    lines.append("  edition_number = EXCLUDED.edition_number,")
    lines.append("  file_path      = EXCLUDED.file_path,")
    lines.append("  description    = EXCLUDED.description,")
    lines.append("  subject_line   = CASE WHEN briefings.subject_line = '' THEN EXCLUDED.subject_line ELSE briefings.subject_line END,")
    lines.append("  body_md        = CASE WHEN briefings.body_md = '' THEN EXCLUDED.body_md ELSE briefings.body_md END;")
    lines.append("")
    lines.append("COMMIT;")

    with open(OUTPUT_SQL, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')

    print(f'Written: {OUTPUT_SQL}')
    for i, (d, rel, _) in enumerate(editions, 1):
        print(f'  {i:3d}. {d}  {rel}')


if __name__ == '__main__':
    main()
